name: "queries"
version: "1.0"
profile: "rj_smas_dev"
model-paths: ["models"]

models:
  queries:
    dashboard_arcgis:
      +materialized: table
      +schema: "{{ 'dashboard_arcgis' if target.name == 'prod' else 'gerenciamento__dbt' }}"
    equipamentos:
      +materialized: table
      +schema: "{{ 'equipamento' if target.name == 'prod' else 'gerenciamento__dbt' }}"
    dashboard_acolherio:
      +materialized: table
      +schema: "{{ 'acolherio' if target.name == 'prod' else 'dashboard_acolherio' }}"
    rma:
      +schema: "{{ 'acolherio' if target.name == 'prod' else 'gerenciamento__dbt' }}"
      cras:
          raw:
            +materialized: ephemeral
          staging:
            +materialized: ephemeral
          intermediate:
            +materialized: incremental
          mart:
            +materialized: incremental
            +schema: "{{ 'dashboard_arcgis' if target.name == 'prod' else 'relatorio' }}"
    bolsa_familia:
      +materialized: table
      +schema: "{{ 'bolsa_familia' if target.name == 'prod' else 'gerenciamento__dbt' }}"
    pic:
      +materialized: table
      +schema: "{{ 'pic' if target.name == 'prod' else 'gerenciamento__dbt' }}"