name: "queries"
version: "1.0"
profile: "rj_smas_dev"
model-paths: ["models"]

models:
  queries:
    dashboard_arcgis:
      materialized: table
      +schema: "{{ 'dashboard_arcgis' if target.name == 'prod' else 'gerenciamento__dbt' }}"
    equipamentos:
      materialized: table
      +schema: "{{ 'equipamentos' if target.name == 'prod' else 'gerenciamento__dbt' }}"
    dashboard_acolherio:
      materialized: table
      +schema: "{{ 'acolherio' if target.name == 'prod' else 'gerenciamento__dbt' }}"
