rj_smas_dev:
  # alvo-padrão para quem for rodar local: DEV
  target: dev
  outputs:

    prod:         
      type: bigquery
      method: service-account
      project: rj-smas-dev
      dataset: gerenciamento__dbt
      keyfile: "{{ env_var('DBT_KEYFILE_PATH') }}"
      threads: 10
      location: US
      timeout_seconds: 300

    dev:
      type: bigquery
      method: service-account
      project: rj-smas-dev
      dataset: gerenciamento__dbt
      keyfile: "{{ env_var('DBT_KEYFILE_PATH') }}"
      threads: 10
      location: US
      timeout_seconds: 300

    ci:                       
      type: bigquery
      method: oauth           
      project: rj-smas-dev    
      dataset: gerenciamento__dbt
      threads: 10
      location: US