-- Camada Raw: familia
with source as (
    select
        id_prefeitura,
        id_cras_creas,
        id_comunidade_quilombola,
        id_familia_indigena,
        familia_indigena,
        id_familia,
        id_indigena_residente,
        indigena_residente,
        id_povo_indigena,
        id_reserva_indigena,
        data_risco_inseguranca_alimentar,
        data_risco_violacao_direitos,
        nao_sabe_comunidade_quilombola,
        nao_tem_despesa_agua_esgoto,
        nao_tem_despesa_alimentacao,
        nao_tem_despesa_aluguel,
        nao_tem_despesa_energia,
        nao_tem_despesa_gas,
        nao_tem_despesa_medicamentos,
        nao_tem_despesa_transporte,
        id_familia_quilombola,
        familia_quilombola,
        nao_tem_pessoas_internadas_0_17_anos,
        nao_tem_pessoas_internadas_18_59_anos,
        nao_tem_pessoas_internadas_mais_60_anos,
        nao_sabe_reserva_indigena,
        id_risco_inseguranca_alimentar,
        risco_inseguranca_alimentar,
        id_risco_violacao_direitos,
        risco_violacao_direitos,
        cras_creas,
        comunidade_quilombola,
        estabelecimento_saude,
        povo_indigena,
        reserva_indigena,
        id_estabelecimento_saude,
        numero_registro_arquivo,
        despesa_agua_esgoto_original,
        despesa_alimentacao_original,
        despesa_aluguel_original,
        despesa_energia_original,
        despesa_gas_original,
        despesa_medicamentos_original,
        despesa_transporte_original,
        versao_layout,
        data_particao
    from {{ source('cadunico', 'familia') }}
)

select * from source
