-- Camada Raw: condicao_rua
with source as (
    select
        id_prefeitura,
        id_carteira_assinada,
        condicao_rua_contato_parente,
        id_familia,
        id_tempo_municipio,
        id_tempo_rua,
        condicao_rua_vive_familia,
        atendido_crentro_referencia_populacao_rua,
        atendido_cras,
        atendido_creas,
        atendido_hospital_geral,
        atendido_instituicao_governamental,
        atendido_instituicao_nao_governamental,
        atendido_nenhum,
        atividade_comunitaria_associacao,
        atividade_comunitaria_cooperativa,
        atividade_comunitaria_escola,
        atibidade_comunitaria_movimento_social,
        atividade_comunitaria_nao_respondeu,
        atividade_comunitaria_nao_sabe,
        ganha_dinheiro_carregador,
        ganha_dinheiro_catador,
        ganha_dinheiro_construcao_civil,
        ganha_dinheiro_flanelinha,
        ganha_dinheiro_nao_respondeu,
        ganha_dinheiro_outro,
        ganha_dinheiro_pedinte,
        ganha_dinheiro_sevicos_gerais,
        ganha_dinheiro_vendas,
        dorme_albergue,
        dorme_domicilio_particular,
        dorme_rua,
        condicao_rua_alcool,
        condicao_rua_ameaca,
        condicao_rua_desemprego,
        condicao_rua_nao_respondeu,
        condicao_rua_nao_sabe,
        condicao_rua_outro,
        condicao_rua_perda_moradia,
        condicao_rua_preferencia,
        condicao_rua_problemas_familiares,
        condicao_rua_saude,
        condicao_rua_trabalho,
        dorme_outro,
        id_membro_familia,
        numero_registro_arquivo,
        id_versao_layout_arquivo,
        data_particao
    from {{ source('cadunico', 'condicao_rua') }}
)

select * from source
