-- Camada Raw: identificacao_controle
with source as (
    select
        id_prefeitura,
        id_condicao_cadastro,
        condicao_cadastro,
        id_estado_cadastro,
        estado_cadastro,
        id_familia,
        id_forma_coleta,
        forma_coleta,
        id_distrito,
        id_setor_censitario,
        id_subdistrito,
        id_modalidade,
        id_mot_impossib_visita_fam,
        mot_impossib_visita_fam,
        id_uf,
        id_municipio,
        id_familia_origem,
        id_prefeitura_origem,
        id_unidade_territorial,
        cpf_usu_alt_fam,
        data_alteracao,
        data_atualizacao,
        data_catrastro as data_cadastro,
        complemento_adicional,
        complemento,
        data_limite_catastro_atual as data_limite_cadastro,
        data_entrevista,
        data_integracao_escolaridade,
        data_integracao_familia,
        filler,
        id_alterada_v7,
        alterada_v7,
        id_cadastro_valido,
        cadastro_valido,
        formulario_0,
        formulario_1,
        formulario_2,
        formulario_suplementar_1,
        formulario_suplementar_2,
        formulario_suplementar_3,
        id_trabalho_infantil,
        trabalho_infantil,
        entrevistador,
        localidade,
        logradouro,
        tipo_logradouro,
        titulo_logradouro,
        unidade_territorial,
        origem_cadastro,
        cep,
        cpf_entrevistador,
        numero_registro_arquivo as numero_registro,
        observacoes_entrevistador,
        refencia_logradouro as referencia_logradouro,
        valor_renda_media_original,
        versao_layout,
        data_particao
    from {{ source('cadunico', 'identificacao_controle') }}
)

select * from source
