-- Camada Raw: representante_legal
with source as (
    select
        id_prefeitura_representante_legal as id_prefeitura,
        id_representante_legal as id_representante,
        id_familia_representante_legal as id_familia,
        id_minicipio_nascimento_representante_legal as id_municipio_nascimento,
        id_pais_nascimento_representante_legal as id_pais_nascimento,
        id_sexo_representante_legal as id_sexo,
        sexo_representante_legal as sexo,
        descricao_complemento_logradouro_representante_legal as complemento_logradouro,
        descricao_representacao_legal as descricao_representacao,
        data_cadastro_representante_legal as data_cadastro,
        data_nascimento_representante_legal as data_nascimento,
        email_representante_legal as email,
        id_obito_acatado_representante_legal as id_obito_acatado,
        obito_acatado_representante_legal as obito_acatado,
        id_obito_representante_legal as id_obito,
        obito_representante_legal as obito,
        nao_sabe_nome_mae_representante_legal as nao_sabe_nome_mae,
        nao_sabe_nome_pai_representante_legal as nao_sabe_nome_pai,
        mae_representante_legal as nome_mae,
        pai_representante_legal as nome_pai,
        representante_legal as nome,
        bairro_representante_legal as bairro,
        logradouro_representante_legal as logradouro,
        municipio_nascimento_representante_legal as municipio_nascimento,
        municipio_representante_legal as municipio,
        pais_nascimento_representante_legal as pais_nascimento,
        tipo_logradouro_representante_legal as tipo_logradouro,
        cep_representante_legal as cep,
        cpf_representante_legal as cpf,
        contato_ddd_representante_legal as ddd,
        contato_ddd_2_representante_legal as ddd_2,
        nis_representante_legal as nis,
        numero_registro_arquivo as numero_registro,
        id_interno_representante_legal as id_interno,
        contato_telefone_representante_legal as telefone,
        contato_telefone_2_representante_legal as telefone_2,
        id_municipio_representante_legal as id_municipio,
        sigla_uf_nascimento_representante_legal as uf_nascimento,
        sigla_uf_representante_legal as uf,
        id_tipo_representacao_legal as id_tipo_representacao,
        tipo_representacao_legal as tipo_representacao,
        versao_layout,
        data_particao
    from {{ source('cadunico', 'representante_legal') }}
)

select * from source
