-- Camada Raw: condicao_rua
with source as (
    select
        id_prefeitura,
        id_carteira_assinada,
        condicao_rua_contato_parente as tem_contato_parente,
        id_familia,
        id_tempo_municipio,
        id_tempo_rua,
        condicao_rua_vive_familia as vive_com_familia,
        atendido_crentro_referencia_populacao_rua as atendido_centro_referencia,
        atendido_cras,
        atendido_creas,
        atendido_hospital_geral,
        atendido_instituicao_governamental,
        atendido_instituicao_nao_governamental,
        atendido_nenhum,
        atividade_comunitaria_associacao,
        atividade_comunitaria_cooperativa,
        atividade_comunitaria_escola,
        atibidade_comunitaria_movimento_social as atividade_comunitaria_movimento_social,
        atividade_comunitaria_nao_respondeu,
        atividade_comunitaria_nao_sabe,
        ganha_dinheiro_carregador,
        ganha_dinheiro_catador,
        ganha_dinheiro_construcao_civil,
        ganha_dinheiro_flanelinha,
        ganha_dinheiro_nao_respondeu,
        ganha_dinheiro_outro,
        ganha_dinheiro_pedinte,
        ganha_dinheiro_sevicos_gerais as ganha_dinheiro_servicos_gerais,
        ganha_dinheiro_vendas,
        dorme_albergue,
        dorme_domicilio_particular,
        dorme_rua,
        condicao_rua_alcool as motivo_alcool,
        condicao_rua_ameaca as motivo_ameaca,
        condicao_rua_desemprego as motivo_desemprego,
        condicao_rua_nao_respondeu as motivo_nao_respondeu,
        condicao_rua_nao_sabe as motivo_nao_sabe,
        condicao_rua_outro as motivo_outro,
        condicao_rua_perda_moradia as motivo_perda_moradia,
        condicao_rua_preferencia as motivo_preferencia,
        condicao_rua_problemas_familiares as motivo_problemas_familiares,
        condicao_rua_saude as motivo_saude,
        condicao_rua_trabalho as motivo_trabalho,
        dorme_outro,
        id_membro_familia as id_membro,
        numero_registro_arquivo as numero_registro,
        id_versao_layout_arquivo,
        data_particao
    from {{ source('cadunico', 'condicao_rua') }}
)

select * from source
