-- Camada Raw: seguranca_alimentar
with source as (
    select
        id_prefeitura,
        id_conta_energia_numero_ordem,
        id_conta_energia_unidade_consumidora,
        id_trabalho_escravo,
        id_familia,
        enegia_doacao as energia_doacao,
        nao_pagou_instalacao_energia,
        energia_nenhum,
        energia_tarifa_social,
        id_ind_parc_mds_fam,
        ind_parc_mds_fam,
        nao_beneficiaria_programa_ministerio_cidades,
        sesan_capitacao_agua_chuva_producao_alimentos,
        sesan_cisterna,
        sesan_vende_feira_popular_mds,
        sesan_horta_comunitaria,
        sesan_nenhum,
        sesan_participou_curso_alimentacao_nutricao,
        sesan_projeto_carteira_indigena,
        sesan_recebe_alimento_paa,
        sesan_recebe_cesta_basica,
        sesan_recebe_leite,
        sesan_refeicao_cozinha_comunitaria,
        sesan_refeicao_restaurante_popular,
        sesan_vende_alimento_paa,
        sesan_vende_leite,
        snas_abrigo_adultos,
        snas_abrigo_crianca_adolescente,
        snas_abrigo_idoso,
        snas_abrigo_mulher_vitima_violencia,
        snas_abrigo_populacao_adulta,
        snas_adolescente_liberdade_servico_comunitario,
        snas_adolescente_liberdade_assistida,
        snas_atendimento_domiciliar_idoso_deficiente,
        snas_bpc_deficiente,
        snas_bpc_idoso,
        snas_centro_dia_idoso,
        snas_crianca_0_6_anos,
        snas_enfrenta_violencia_crianca,
        snas_gtupos_idosos as snas_grupos_idosos,
        snas_habilitacao_reabilitacao_deficiencia,
        snas_inclusao_produtiva,
        snas_nunhum as snas_nenhum,
        snas_orientacao_especial_crianca_adolescente,
        snas_programa_atencao_integram_familia,
        snas_programa_erradicacao_trabalho_infantil,
        snas_projovem_adolescente,
        snas_projovem_campo,
        snas_projovem_trabalhador,
        snas_projovem_urbano,
        numero_registro_arquivo as numero_registro,
        versao_layout,
        data_particao
    from {{ source('cadunico', 'seguranca_alimentar') }}
)

select * from source
