-- Camada Raw: trabalho_remuneracao
with source as (
    select
        id_prefeitura,
        id_afastado_semana_passada,
        id_atividade_extravista,
        id_familia,
        id_origem_valor_outra_fonte,
        origem_valor_outra_fonte,
        id_origem_valor_pensao_alimenticia,
        origem_valor_pensao_alimenticia,
        id_origem_valor_rendimento_bruto,
        origem_valor_rendimento_bruto,
        id_origem_valor_rendimento_mes_passado,
        origem_valor_rendimento_mes_passado,
        id_origem_valor_seguro_desemprego,
        origem_valor_seguro_desemprego,
        id_origem_valor_ajuda_doacao,
        origem_valor_ajuda_doacao,
        id_origem_valor_aposentadoria,
        origem_valor_aposentadoria,
        id_funcao_principal_trabalho,
        funcao_principal_trabalho,
        id_trabalho_remunerado_ultimos_12_meses,
        id_trabalho_semana_passada,
        data_integracao_aposentadoria,
        data_integracao_outras_fonte,
        data_integracao_renda_bruta_12_meses,
        data_integracao_emprego_ultimo_mes,
        nao_recebe_outras_fontes,
        nao_recebe_remuneracao,
        nao_recebe_aposentadoria,
        nao_recebe_doacao,
        nao_recebe_pensao_alimenticia,
        nao_recebe_seguro_desemprego,
        id_membro_familia,
        numero_registro_arquivo,
        outras_fontes_original,
        remuneracao_original,
        aposentadoria_original,
        remuneracao_bruta_original,
        doacoes_original,
        pensao_alimenticia_original,
        seguro_desemprego_original,
        versao_layout,
        data_particao
    from {{ source('cadunico', 'trabalho_remuneracao') }}
)

select * from source
