version: 2

sources:
  - name: bolsa_familia_staging
    description: "Dados brutos do Bolsa Família carregados via pipeline Python"
    schema: "bolsa_familia_staging"
    tables:
      - name: folha
        description: "Tabela contendo a linha bruta do arquivo, timestamp e partição"
