{% macro map_violacao_direito_descricao(codigo) %}
    CASE
        WHEN {{ codigo }} = '01' THEN 'Violação Sexual'
        WHEN {{ codigo }} = '02' THEN 'Violência psicológica'
        WHEN {{ codigo }} = '03' THEN 'Violência financeira ou patrimonial'
        WHEN {{ codigo }} = '04' THEN 'Negligência e abandono'
        WHEN {{ codigo }} = '05' THEN 'Violência medicamentosa'
        WHEN {{ codigo }} = '06' THEN 'Violência doméstica'
        WHEN {{ codigo }} = '07' THEN 'Violência por tráfico de seres humanos'
        WHEN {{ codigo }} = '08' THEN 'Violência por trabalho escravo'
        WHEN {{ codigo }} = '09' THEN 'Violência institucional'
        WHEN {{ codigo }} = '10' THEN 'Adoção Ilegal'
        WHEN {{ codigo }} = '11' THEN 'Afastamento do convívio familiar devido a aplicação de MSE ou medida de proteção'
        WHEN {{ codigo }} = '12' THEN 'Auto Negligência'
        WHEN {{ codigo }} = '13' THEN 'Cárcere Privado'
        WHEN {{ codigo }} = '14' THEN 'Conflitos Territoriais / Conflitos Urbanos'
        WHEN {{ codigo }} = '15' THEN 'Discriminação Étnica/Racial'
        WHEN {{ codigo }} = '16' THEN 'Discriminação Religiosa'
        WHEN {{ codigo }} = '17' THEN 'Discriminação Sexual / Gênero'
        WHEN {{ codigo }} = '18' THEN 'Exploração Sexual'
        WHEN {{ codigo }} = '19' THEN 'Outras violências sexuais'
        WHEN {{ codigo }} = '20' THEN 'Trabalho Infantil'
        WHEN {{ codigo }} = '21' THEN 'Violência em razão de questões de saúde mental'
        WHEN {{ codigo }} = '22' THEN 'Violência Física'
        WHEN {{ codigo }} = '23' THEN 'Violência Obstétrica'
        WHEN {{ codigo }} = '24' THEN 'Vítima de Tráfico de Órgãos'
        WHEN {{ codigo }} = '25' THEN 'Situação de grave ameaça no território'
        WHEN {{ codigo }} = '28' THEN 'Violência Intrafamiliar'
        WHEN {{ codigo }} = '27' THEN 'Já Passou por Violações de direitos antes'
        WHEN {{ codigo }} = '26' THEN 'Outras Violações de Direitos'
        ELSE 'Código Desconhecido'
    END
{% endmacro %}
